### Unión de archivos de Pronóstico de Generación Intermitente ###

En esta notebook se leen todos los archivos fuente en formato CSV de los Pronósticos de Generación Intermitentes calculados por el CENACE y presentados por Tipo de Tecnología y se unen para generar un dataframe con todos los datos históricos. Después se exportan a un archivo en formato excel. 

Se asume que todos los archivos a unir tienen la misma estructura.

URL: https://www.cenace.gob.mx/Paginas/SIM/Reportes/PronosticoGeneracionInter.aspx

In [14]:
# Importación de librerias requeridas
import pandas as pd
import glob
from datetime import datetime
import warnings
import re
warnings.filterwarnings("ignore")

In [6]:
# Definir la ruta en donde se ubican los archivos fuente
path = r"D:\Nueva carpeta\Gen_intermitente"

# se guardan todas las rutas
all_files = glob.glob(path + "/*.csv")

In [25]:
# Se define una matriz que indica las filas de los frames, 1 frame por archivo
li = []

# Expresión regular para extraer la fecha
patron = r'\d{4}-\d{2}-\d{2}'

# Ciclo for para la lectura de cada uno de los archivos
for filename in all_files:    
    df = pd.read_csv(filename, header=7, index_col=False)
    df["Fecha"] = re.search(patron, filename).group()
    # Se unen las listas 
    li.append(df)

# Frame integrada por todos los archivos del directorio
frame = pd.concat(li, axis=0, ignore_index=True)

# Cambiar el orden de las columnas
orden_columnas = ['Sistema', ' Tipo de Tecnologia', 'Fecha',' Hora',' Pronostico de Generacion (MWh)']  
frame = frame[orden_columnas]


# Convertir la columna 'Fecha' a datetime
frame['Fecha'] = pd.to_datetime(frame['Fecha'])

In [31]:
# Imprime dataframe
frame

,Sistema,Tipo de Tecnologia,Fecha,Hora,Pronostico de Generacion (MWh)
0,BCA,EOLICA,2024-03-01,1,24.174
1,BCA,EOLICA,2024-03-01,2,23.750
2,BCA,EOLICA,2024-03-01,3,22.056
3,BCA,EOLICA,2024-03-01,4,20.941
4,BCA,EOLICA,2024-03-01,5,18.877
...,...,...,...,...,...
715,SIN,FOTOVOLTAICA,2024-03-05,20,16.063
716,SIN,FOTOVOLTAICA,2024-03-05,21,8.007
717,SIN,FOTOVOLTAICA,2024-03-05,22,0.005
718,SIN,FOTOVOLTAICA,2024-03-05,23,0.000
719,SIN,FOTOVOLTAICA,2024-03-05,24,0.000

In [29]:
# info general del dataframe
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 5 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sistema                          720 non-null    object
 1    Tipo de Tecnologia              720 non-null    object
 2   Fecha                            720 non-null    datetime64[ns]
 3    Hora                            720 non-null    int64
 4    Pronostico de Generacion (MWh)  720 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 28.2+ KB

In [30]:
# exporta el dataframe a un archivo excel en un ruta determinada

# Ruta donde deseas guardar el archivo de Excel
ruta_excel = r'D:\Nueva carpeta\Gen_intermitente\Datos_Generacion_Intermitente.xlsx'

# Exportar el DataFrame a un archivo de Excel en la ruta especificada
frame.to_excel(ruta_excel, index=False)